export type Language = "ru" | "en";

export const copy = {
  ru: {
    nav: {
      work: "Работы",
      about: "Подход",
      contact: "Контакты",
      admin: "Панель",
      primaryLabel: "Основная навигация",
      languageLabel: "Язык",
      topLabel: "Matvix — наверх",
    },
    hero: {
      eyebrow: "Моушн-дизайнер · Видеомонтажёр",
      lineOne: "МОНТАЖ,",
      lineTwo: "КОТОРЫЙ",
      lineThree: "ДВИГАЕТ",
      statement:
        "Монтаж и моушн-дизайн, которые удерживают внимание и работают на задачи бренда.",
      explore: "Смотреть портфолио",
      availability: "Доступен для проектов",
      scroll: "Листайте",
      code: "MVX / 001",
    },
    reel: {
      eyebrow: "Избранные работы · 2025—2026",
      title: "Избранные работы",
      intro:
        "Девять проектов. В каждом темп, драматургия, звук и графика работают как единое целое.",
      view: "Открыть работу",
    },
    cases: [
      {
        title: "Pulse",
        type: "Продуктовый моушн",
        note: "Ритм продукта собран в ясную визуальную историю.",
      },
      {
        title: "Signal",
        type: "Бренд-фильм",
        note: "Монтаж, который держит внимание без визуального шума.",
      },
      {
        title: "Nocturne",
        type: "Рекламный монтаж",
        note: "Атмосфера превращена в узнаваемый язык бренда.",
      },
      {
        title: "Kinetic",
        type: "Титры · Моушн",
        note: "Типографика становится главным героем кадра.",
      },
    ],
    about: {
      eyebrow: "Как я работаю",
      title: "Меньше шума.\nБольше смысла.",
      body:
        "Я выстраиваю темп, визуальный образ и звук вокруг задачи клиента — и убираю всё лишнее.",
      facts: [
        ["01", "Погружаюсь в задачу"],
        ["02", "Выстраиваю драматургию"],
        ["03", "Довожу каждый кадр"],
      ],
      portraitAlt: "Матвей, моушн-дизайнер и видеомонтажёр",
      portraitLabel: "ПОРТРЕТ / 01",
      portraitRole: "МОУШН-ДИЗАЙН · МОНТАЖ",
    },
    orbit: {
      eyebrow: "Эксперименты",
      title: "Ещё\nработы",
      hint: "Потяните, чтобы вращать",
    },
    contact: {
      eyebrow: "Обсудим проект",
      title: "Есть задача?\nДавайте обсудим.",
      telegram: "Написать в Telegram",
      mail: "Скопировать email",
      copied: "Email скопирован",
      paste: "Готово — можно вставить",
      note: "Отвечаю лично · обычно в течение дня",
    },
    principle: {
      label: "02 / ПРИНЦИП",
      title: "РИТМ РЕШАЕТ",
      body: "Каждый переход, пауза и звук подчинены одной задаче — удержать внимание.",
      ariaLabel: "Творческий принцип",
    },
    admin: {
      eyebrow: "Локальная панель",
      title: "Управление видео",
      note:
        "Ролики сохраняются только в этом браузере и сразу появляются в портфолио. Создайте резервную копию, чтобы перенести их на другое устройство.",
      libraryTitle: "Локальные видео",
      upload: "Добавить видео",
      uploading: "Сохраняем видео…",
      uploadSuccess: "Видео сохранены в локальной библиотеке.",
      empty: "Загруженных роликов пока нет.",
      remove: "Удалить",
      close: "Закрыть",
      clear: "Очистить всё",
      replay: "Повторить заставку",
      stored: "Сохранено в браузере",
      transferTitle: "Передача панели",
      transferNote:
        "Скачайте один файл .matvix-backup и передайте его другому человеку. После импорта он получит точную копию локальной видеотеки.",
      exportBackup: "Скачать копию",
      importBackup: "Импортировать",
      exporting: "Создаём копию…",
      importing: "Проверяем копию…",
      exportSuccess: "Резервная копия скачана.",
      importSuccess: "Резервная копия проверена и восстановлена.",
      removeSuccess: "Видео удалено.",
      clearSuccess: "Локальная видеотека очищена.",
      confirmImport:
        "Импорт заменит все локально загруженные видео в этом браузере. Продолжить?",
      confirmRemove: "Удалить видео «{name}» из этого браузера?",
      confirmClear: "Удалить все локально загруженные видео? Это действие нельзя отменить.",
      errorUnsupportedVideo: "Поддерживаются только MP4, WebM и MOV.",
      errorVideoTooLarge: "Один видеофайл не должен превышать 250 МБ.",
      errorTooManyVideos: "В локальной видеотеке может быть не более 50 роликов.",
      errorTotalTooLarge: "Общий объём локальных видео не должен превышать 1 ГБ.",
      errorInvalidVideo: "Видео пустое, повреждено или имеет недопустимое имя.",
      errorStorage: "Браузер не смог сохранить данные. Проверьте свободное место.",
      errorNothingToExport: "Нет локальных видео для резервного копирования.",
      errorBackupTooLarge: "Файл резервной копии превышает допустимый размер.",
      errorBackupVersion: "Эта версия резервной копии пока не поддерживается.",
      errorBackupCorrupted: "Резервная копия повреждена: проверка данных не пройдена.",
      errorInvalidBackup: "Это не корректный файл .matvix-backup.",
      errorGeneric: "Не удалось выполнить действие. Попробуйте ещё раз.",
    },
    footer: {
      role: "Моушн-дизайн · Монтаж · Визуальные системы",
      top: "Наверх",
    },
  },
  en: {
    nav: {
      work: "Work",
      about: "Approach",
      contact: "Contact",
      admin: "Admin",
      primaryLabel: "Primary navigation",
      languageLabel: "Language",
      topLabel: "Matvix — back to top",
    },
    hero: {
      eyebrow: "Motion designer · Video editor",
      lineOne: "EDITING",
      lineTwo: "BUILT TO",
      lineThree: "MOVE",
      statement:
        "Editing and motion design that hold attention and deliver on the brief.",
      explore: "View portfolio",
      availability: "Available for projects",
      scroll: "Scroll",
      code: "MVX / 001",
    },
    reel: {
      eyebrow: "Selected work · 2025—2026",
      title: "Selected work",
      intro:
        "Nine selected projects where pacing, narrative, sound and motion work as one.",
      view: "Open project",
    },
    cases: [
      {
        title: "Pulse",
        type: "Product motion",
        note: "Product rhythm shaped into a clear visual story.",
      },
      {
        title: "Signal",
        type: "Brand film",
        note: "An edit that holds attention without visual noise.",
      },
      {
        title: "Nocturne",
        type: "Campaign edit",
        note: "Atmosphere translated into a distinctive brand language.",
      },
      {
        title: "Kinetic",
        type: "Title sequence",
        note: "Typography becomes the lead character.",
      },
    ],
    about: {
      eyebrow: "How I work",
      title: "Less noise.\nMore meaning.",
      body:
        "I shape rhythm, image and sound around the client's goal — then remove everything that gets in the way.",
      facts: [
        ["01", "Read the brief"],
        ["02", "Build the narrative"],
        ["03", "Refine every frame"],
      ],
      portraitAlt: "Matvey, motion designer and video editor",
      portraitLabel: "PORTRAIT / 01",
      portraitRole: "MOTION DIRECTION · EDITING",
    },
    orbit: {
      eyebrow: "More experiments",
      title: "More\nwork",
      hint: "Drag to rotate",
    },
    contact: {
      eyebrow: "Start a project",
      title: "Have a project?\nLet's bring it to life.",
      telegram: "Message me on Telegram",
      mail: "Copy email address",
      copied: "Email copied",
      paste: "Ready to paste",
      note: "I reply personally · usually within a day",
    },
    principle: {
      label: "02 / PRINCIPLE",
      title: "RHYTHM MAKES\nIT WORK",
      body: "Every cut, pause and sound serves one goal: hold attention.",
      ariaLabel: "Creative principle",
    },
    admin: {
      eyebrow: "Local studio console",
      title: "Video manager",
      note:
        "Videos stay in this browser and appear in the portfolio immediately. Create a backup to move them to another device.",
      libraryTitle: "Local videos",
      upload: "Add videos",
      uploading: "Saving videos…",
      uploadSuccess: "Videos saved to the local library.",
      empty: "No uploaded videos yet.",
      remove: "Remove",
      close: "Close",
      clear: "Clear all",
      replay: "Replay intro",
      stored: "Stored in this browser",
      transferTitle: "Transfer this panel",
      transferNote:
        "Download one .matvix-backup file and send it to another person. Importing it creates an exact copy of this local video library.",
      exportBackup: "Download backup",
      importBackup: "Import backup",
      exporting: "Creating backup…",
      importing: "Verifying backup…",
      exportSuccess: "Backup downloaded.",
      importSuccess: "Backup verified and restored.",
      removeSuccess: "Video removed.",
      clearSuccess: "Local video library cleared.",
      confirmImport:
        "Importing will replace every locally uploaded video in this browser. Continue?",
      confirmRemove: "Remove “{name}” from this browser?",
      confirmClear:
        "Remove every locally uploaded video? This action cannot be undone.",
      errorUnsupportedVideo: "Only MP4, WebM and MOV videos are supported.",
      errorVideoTooLarge: "Each video must be 250 MB or smaller.",
      errorTooManyVideos: "The local library can contain up to 50 videos.",
      errorTotalTooLarge: "Local videos can use up to 1 GB in total.",
      errorInvalidVideo: "The video is empty, damaged or has an invalid filename.",
      errorStorage: "The browser could not store the data. Check available space.",
      errorNothingToExport: "There are no local videos to back up.",
      errorBackupTooLarge: "The backup file exceeds the allowed size.",
      errorBackupVersion: "This backup version is not supported yet.",
      errorBackupCorrupted: "The backup is damaged and failed its integrity check.",
      errorInvalidBackup: "This is not a valid .matvix-backup file.",
      errorGeneric: "The action could not be completed. Please try again.",
    },
    footer: {
      role: "Motion direction · Editing · Visual systems",
      top: "Back to top",
    },
  },
} as const;

export type SiteCopy = (typeof copy)[Language];
